config/routes.rb
Rails.application.routes.draw do
  resources :users



  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "pages_presentation(/:name)", to: 'pages#salut', as: 'presentation' # Dans le controller nommé pages_controller, méthode salut

  root to: 'pages#home' # Définir la route racine vers pages#home
  resources :posts # Définir les paths
  resources :categories


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
=begin
    Ce modèle représente la table 'posts' dans la base de données.
  
    Le fichier modèle est généré automatiquement avec la commande :
    | rails generate model Post name:string content:text |
    qui crée à la fois une migration pour la table 'posts' et ce fichier modèle 'post.rb'.
  
    En revanche, la commande :
    | rails generate migration Post name:string content:text |
    crée uniquement une migration sans créer le fichier modèle.
=end
end
  


=begin C'est avec Post.new Post.find(1).name = .... |
interagir avec la base de données en fournissant une interface pour lire, écrire, et modifier 
les données.


ApplicationRecord est une classe de base fournie par Rails pour tous les modèles. 
Elle fournit des méthodes pour interagir avec la base de données, telles que all, find, where, etc.

=end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  add_flash_types :danger, :success
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only:[:update,:edit,:show,:destroy] 

  def index
    @session = session[:user_id]
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def salut
    @name = params[:name] || "non-saisie"
  end

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only:[:update,:edit,:show,:destroy]
  after_action :delete_info, only:[:update]


  def index
    cookies.delete(:username) 
    session[:user_id] = {username: 'JO', id:5}
    @posts = Post.all
    respond_to do |format|
      format.html
      format.json {render json: @posts.as_json(only: [:id])} #Triage, on peut également changer la méthode as_json(post.rb)
      format.xml { render xml: @posts}

    end
  end

  def show

    unless @post
      redirect_to posts_path
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to posts_path, success: 'Article  Modifié ! ! ' #crée un la clé success dans le hash flash avec sa valeur
  end

  def new
    @post = Post.new 
    #crée une nouvelle instance de Post, mais ne l'enregistre pas encore dans la base de données.
    # demande de complétion du formaulaire
  end

  def create # Après avoir confirmer l'envoi du formulaire
    @post = Post.create(post_params) #paramètre du formulaire (name, content) | .create a l'option save
    if @post.save #Vérifie si l'enregistrement à bien été save dans la db
      redirect_to posts_path, success: 'Article  Crée ! ! '
    else
      render :new # réaffiche le formulaire de création avec les erreurs de validation.
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: "Article '#{@post.name}' supprimé !"
  end

  private

  def post_params
    params.require(:post).permit(:name, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def delete_info
    p session.inspect
    p "--------------"
    p flash.inspect
  end
end


=begin
 L'action index est généralement responsable de récupérer les données de la base de données (post.rb)
 et de les transmettre à la vue index.html.erb.

 En définissant @post, vous permettez à Rails de transmettre automatiquement cette variable à la vue, 
 où vous pouvez l'utiliser pour afficher les détails de l'article. == Variable global
=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Modification de Catégorie</h1>

<%= form_for @category do |f| %>
  <div class="form-group">
    <label>Titre de la Catégorie</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Nom"%>
  </div>

  <div class="form-group">
    <label>Slug</label>
    <%= f.text_field :slug, class: "form-control" , placeholder: "Url"%>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier la Catégorie</button>
  </div>
<% end %>

app/views/categories/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catégories</title>
  <style>
    h1 {
      color: #007bff;
      text-align: center;
    }
 
    .offset-text {
      padding-left: 30px;
    }

    .container {
      margin-top: 10px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }

    .btn {
      margin-right: 5px;
    }

    .button-group {
      display: flex;
      gap: 5px;
    }
  </style>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <h1>Catégories</h1>
  <p> <%= @session.inspect %> </p>
  <% @categories.each do |categorie| %>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nom</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="offset-text"><%= categorie.id %></td>
          <td class="offset-text"><%= categorie.name %></td>
          <td>
            <div class="button-group">
              <a href="<%= category_path(categorie) %>" class="btn btn-primary">Voir la Catégorie</a>
              <a href="<%= edit_category_path(categorie) %>" class="btn btn-secondary">Modifier</a>
              <%= form_with(model: categorie, method: :delete, local: true) do |form| %>
                <%= form.submit 'Supprimer', data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet article ?' }, class: 'btn btn-danger' %>
              <% end %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>

  <div class="container">
    <a href="<%= new_category_path %>" class="btn btn-success">Créer une catégorie</a>
  </div>
</body>
</html>

app/views/categories/new.html.erb
<h1>Création de Catégorie</h1>

<%= form_for @category do |f| %>
  <div class="form-group">
    <label>Titre de la Catégorie</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Nom"%>
  </div>

  <div class="form-group">
    <label>Slug</label>
    <%= f.text_field :slug, class: "form-control" , placeholder: "Url"%>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Créer la Catégorie</button>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorformation</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  
  <!-- jQuery and Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.amazonaws.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
  <style>
    .p-2 {
      color: white;
    }
    .navbar-dark .navbar-nav .nav-link {
      color: white;
    }
  </style>

  <nav class="navbar navbar-dark bg-dark fixed-top">
    <a class="p-2" href="<%= root_path %>">Page d'accueil</a>
    <a class="p-2" href="<%= presentation_path %>">Pages de Présentation</a>
    <a class="p-2" href="<%= posts_path %>">Articles les villes</a>
    <a class="p-2" href="<%= categories_path %>"> Catégories</a>
  </nav>

  <div class="container" style="padding-top: 5rem">
    <% flash.each do |name, message| %>
      <div class="alert alert-<%=name%>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<h1> Bienvenue sur le site ! </h1>

app/views/pages/salut.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formulaire de nom</title>
</head>
<body>
  <p>Ton nom : <%= @name %></p>
</body>
</html>

app/views/posts/destroy.html.erb
<h1>Article : <%= @post.name %> Supprimé !</h1>

<a href="<%= posts_path %>" class="btn btn-back">Retour</a>

app/views/posts/edit.html.erb
<h1>Modification de l'Article : <%= @post.name %></h1>
<style>  
  .btn-back {
    background-color: red; /* Définir la couleur de fond du bouton en rouge */
    color: white; /* Définir la couleur du texte du bouton en blanc pour le contraste */
    transition: background-color 0.3s, color 0.3s;
  }
  .btn-back:hover {
    background-color: white; /* Couleur de fond au survol en blanc */
    color: red; /* Couleur du texte au survol en rouge */
  }
</style>

<%= form_for @post do |f| %>
  <div class="form-group">
    <label>Titre de l'article</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Contenu</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier l'article</button>
    <a href="<%= posts_path %>" class="btn btn-back">Retour</a>
  </div>

<% end %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <style>
    h1 {
      color: #007bff;
      text-align: center;
    }

    ul {
      list-style-type: none;
      padding: 0;
    }

    li {
      border-bottom: 1px solid #ddd;
      padding: 10px;
      background-size: 20px 20px;
      background-repeat: no-repeat;
      background-position: left center;
    }

    .offset-text {
      padding-left: 30px;
    }

    .container {
      margin-top: 10px;
    }

    <% @posts.each do |post| %>
      <% image_name = post.name.parameterize.downcase %>
      <% image_path = Rails.root.join('app/assets/images/villes', "#{image_name}.png") %>
      <% if File.exist?(image_path) %>
        .post-<%= image_name %> {
          background-image: url('<%= asset_path("villes/#{image_name}.png") %>');
        }
      <% end %>
    <% end %>
  </style>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <h1>Articles</h1>

  <ul>
    <% @posts.each do |post| %>
      <% image_name = post.name.parameterize.downcase %>
      <li class="post-<%= image_name %>">
        <strong class="offset-text"><%= post.name %></strong>: 
        <div class="container">
          <a href="<%= post_path(post) %>" class="btn btn-primary">Lire la suite</a>
          <a href="<%= edit_post_path(post) %>" class="btn btn-secondary">Éditer</a>
          
          <%= form_with(model: post, method: :delete, local: true) do |form| %>
            <%= form.submit 'Supprimer', data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet article ?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </li>
    <% end %>
    <a href="<%= new_post_path %>" class="btn btn-success">Créer un article</a>
  </ul>

  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <%= javascript_importmap_tags %>
</body>
</html>

app/views/posts/new.html.erb
<h1>Création d'Article : </h1>

<%= form_for @post do |f| %> <!-- form_for utilise par défaut la méthode HTTP POST et l'envoi au PostsController grâce à @post-->
                             <!-- Rails sait que c'est un nouvel enregistrement et utilise create-->

<div class="form-group">
  <label> Titre de l'article *</label>
  <%= f.text_field :name, class: "form-control", required: true %>
</div>

<div class="form-group">
  <label> Contenu *</label>
  <%= f.text_area :content, class: "form-control", required: true %>
</div>


  <div class="form-group">
   <button type="submit" class="btn btn-primary">Créer l'article</button>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Article : <%= @post.name %> </h1>

<p>Contenu : <%= @post.content %></p>

<p><a href="<%= posts_path %>" class="btn btn-primary">Revenir aux Articles</a></p>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-secondary' %>